#!/bin/bash
chown --from=guillaume betty hello
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
102-if_only [unix] (00:59 01/01/1970)                                  0,0-1 All
"102-if_only" [New]

~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
102-if_only [unix] (00:59 01/01/1970)                                  0,0-1 All
"102-if_only" [New]

